# National College Portal - Nginx Configuration

worker_processes auto;

events {
    worker_connections 4096;
}

http {
    include C:\\nginx\\nginx-1.30.3\\conf\\mime.types;
    default_type  application/octet-stream;

    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;
    keepalive_timeout 65;
    keepalive_requests 1000;

    client_max_body_size 100M;

    gzip on;
    gzip_comp_level 6;
    gzip_min_length 1024;

    gzip_types
        text/plain
        text/css
        application/json
        application/javascript
        application/xml
        application/pdf;

    server {
        listen 80;
        server_name localhost;

        #
        # Static PDFs
        #
        root C:/Users/vamsi/clg-uploads;

        location /results/ {
            default_type application/pdf;

            add_header Content-Disposition inline;
            add_header Cache-Control "public, max-age=86400";

            access_log off;
            expires 1d;
        }

        #
        # Static General Uploads (Media)
        #
        location /uploads/ {
            add_header Cache-Control "public, max-age=86400";
            access_log off;
            expires 30d;
        }

        #
        # Next.js
        #
        location / {
            proxy_pass http://127.0.0.1:3000;

            proxy_http_version 1.1;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";

            proxy_read_timeout 300;
            proxy_send_timeout 300;
        }
    }
}