-- Insert sample departments
INSERT INTO departments (name, code, short_name, icon, description, overview, is_active, sort_order, established_year, vision, mission) VALUES
  ('Computer Science', 'CS', 'CSE', 'Monitor', 'Department of Computer Science and Engineering', 'The Computer Science department offers cutting-edge programs in software development, AI, and data science.', true, 1, 1990, 'To be a globally recognized center of excellence in computer science education and research.', 'To produce competent computer science professionals through quality education, research, and industry collaboration.'),
  ('Electronics & Communication', 'EC', 'ECE', 'Cpu', 'Department of Electronics and Communication Engineering', 'ECE department focuses on embedded systems, VLSI design, and communication technologies.', true, 2, 1985, 'To excel in electronics and communication engineering education and research.', 'To develop skilled engineers who can contribute to technological advancements in electronics.'),
  ('Mechanical Engineering', 'ME', 'Mech', 'Wrench', 'Department of Mechanical Engineering', 'Mechanical Engineering department specializes in manufacturing, design, and thermal engineering.', true, 3, 1975, 'To be a leading mechanical engineering department with global recognition.', 'To impart quality education and develop innovative engineers for industrial advancement.'),
  ('Mathematics', 'MA', 'Math', 'Calculator', 'Department of Mathematics', 'The Mathematics department provides foundational and advanced mathematical education.', true, 4, 1965, 'To be a center of excellence in mathematical sciences.', 'To develop mathematical thinking and analytical skills among students.'),
  ('Physics', 'PH', 'Phys', 'Atom', 'Department of Physics', 'Physics department offers programs in theoretical and applied physics.', true, 5, 1965, 'To advance knowledge in physics through teaching and research.', 'To create scientifically aware citizens and skilled physicists.'),
  ('Chemistry', 'CH', 'Chem', 'FlaskConical', 'Department of Chemistry', 'Chemistry department focuses on organic, inorganic, and physical chemistry.', true, 6, 1965, 'To excel in chemical sciences education and research.', 'To develop quality chemists for industry and research.'),
  ('Commerce', 'CO', 'Commerce', 'Building2', 'Department of Commerce', 'Commerce department offers programs in accounting, finance, and business management.', true, 7, 1970, 'To be a premier institution for commerce education.', 'To prepare students for successful careers in commerce and finance.'),
  ('Management Studies', 'MB', 'MBA', 'Briefcase', 'Department of Management Studies', 'Management department prepares future business leaders with practical skills.', true, 8, 1985, 'To be a leading management education institution.', 'To develop competent managers with ethical values.'),
  ('English', 'EN', 'Eng', 'BookOpen', 'Department of English', 'English department focuses on literature, language, and communication skills.', true, 9, 1965, 'To excel in English language and literature education.', 'To enhance communication skills and literary appreciation.');